bayesimpact/docker-react

- Dockerfile
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/docker-react/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/docker-react/pulls/assigned/florianjourda">florianjourda</a>
> Fix npm updates in derived Docker due to https://github.com/npm/npm/issues/9863 . Also optimizes Docker layers.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/docker-react/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/docker-react/pulls/assigned/florianjourda">florianjourda</a>
> Use trusty and not xenial for base.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/6)
> Really install latest nodejs and NPM

- README.md
+@pcorpet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/9)
> Add more instructions to README

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/10)
> Add a badge on README that shows the size and # of layers of our image.

- Dockerfile
- README.md
- cfg/base.js
- cfg/dev.js
- cfg/dist.js
- cfg/test.js
- package.json
- server.js
- webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/35)
> Embed a basic webpack config so that setup is slightly faster.

- Dockerfile
- cfg/dev.js
- cfg/dist.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/42)
> Fix default server setup for a project with no config files explicitly mounted.

- .babelrc
- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/44)
> Add a default .babelrc file.

- .babelrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/66)
> Keep CommonJS modules: we are not ready for full tree shaking yet.

- Dockerfile
- README.md
- cfg/base.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/80)
> Make it simpler to start a new project based on this container.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/84)
> Add img-loader to compress images with Webpack on the fly.

- Dockerfile
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/85)
> Use node base container to simplify the Dockerfile.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/91)
> Add Firebase.

- package.json
- server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/113)
> Fix indentation and switch to eslint v4.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/136)
> Remove ReactTransitionGroup dep that nobody uses.

- package.json
Upgrade dependency react-addons-test-utils to 15.6.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/191)
> Add some more packages we have started to use.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/239)
> Do not reference the copy script as it does not exist.

- package.json
Upgrade dependency webpack-dev-server to 2.9.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/258)
> Replacing mdi with mdi-react.

- cfg/dev.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/265)
> Fix the cfg/dev for react hot loader v3.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/277)
> [Clean libs] Remove color since it isn't used in our projects anymore.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/325)
> Update to node 9.3 and use yarn instead of npm.

- package.json
Add new packages used by Bob.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/336)
> Add svgo as a direct dependency, it's required as a peer dependency by svgo-loader.

- .babelrc
- package.json
Add new packages used by Bob.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/335)
> Migrate to babel-preset-env from deprecated babel-preset-es2015. See http://babeljs.io/env for migration instructions.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/348)
> Add yarn-lazy-lock to be able to use yarn while reusing installed packages.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/358)
> Install rename-output-webpack-plugin

- package.json
This reverts commit b4539626055978719ae3b24d4843be98065bc8fb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/382)
> Revert "[Doppins] Upgrade dependency eslint to 4.18.0 (#376)"

- webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/434)
> Trace deprecation so that those messages are less obscure.

- package.json
Upgrade dependency autocomplete.js to 0.28.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/452)
> Add the Amplitude SDK.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/505)
> Upgrade to latest yarn-lazy-lock 0.1.1

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/504)
> Upgrade base to node:10.1.0

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/532)
> Adding randexp lib.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/597)
> Drop jimp dep, we don't use it anymore.

- package.json
This reverts commit 7b84d65ff96fae4ab4e8e6842297fbb064db23c1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/622)
> Revert "[Doppins] Upgrade dependency url-loader to 1.1.1 (#585)"

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/664)
> Update url-loader by hand.

- CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/687)
> Adding mlendale as reviewer.

- cfg/dev.js
- cfg/dist.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/751)
> Make sure the PWA plugin is added at the end of the plugins list to properly register inside the HTML.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/894)
> [Update] Upgrade node version to 11.12.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/992)
> [Clean Deps] Drop unused `open`.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1034)
> Add types for lodash.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1041)
> [Replace-Doppins] Update redux to 4.0.3

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1042)
> Update react-hot-reloader to 4.12.9.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1043)
> [AutoUpdate] Update dependency @babel/core to version 7.5.5.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1045)
> [AutoUpdate] Update dependency @babel/preset-env to version 7.5.5.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1044)
> [AutoUpdate] Update dependency @babel/plugin-proposal-class-properties to version 7.5.5.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1046)
> [AutoUpdate] Update dependency @mysticatea/eslint-plugin to version 11.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1047)
> [AutoUpdate] Update dependency @types/lodash to version 4.14.136.

- doppins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1095)
> [Doppins Replacement] Add a script to replace Doppins.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1051)
> [AutoUpdate] Update dependency @types/webpack-env to version 1.14.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1054)
> [AutoUpdate] Update dependency airtable to version 0.7.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1055)
> [AutoUpdate] Update dependency babel-eslint to version 10.0.2.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1068)
> [AutoUpdate] Update dependency firebase to version 6.3.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1080)
> [AutoUpdate] Update dependency query-string to version 6.8.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1069)
> [AutoUpdate] Update dependency firebase-tools to version 7.2.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1057)
> [AutoUpdate] Update dependency copyfiles to version 2.1.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1059)
> [AutoUpdate] Update dependency detect-browser to version 4.6.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1072)
> [AutoUpdate] Update dependency karma to version 4.2.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1079)
> [AutoUpdate] Update dependency puppeteer to version 1.19.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1070)
> [AutoUpdate] Update dependency google-protobuf to version 3.9.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1074)
> [AutoUpdate] Update dependency karma-webpack to version 4.0.2.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1077)
> [AutoUpdate] Update dependency mocha to version 6.2.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1060)
> [AutoUpdate] Update dependency es6-promise to version 4.2.8.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1056)
> [AutoUpdate] Update dependency connected-react-router to version 6.5.2.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1090)
> [AutoUpdate] Update dependency typescript to version 3.5.3.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1084)
> [AutoUpdate] Update dependency react-markdown to version 4.1.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1076)
> [AutoUpdate] Update dependency mdi-react to version 5.5.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1091)
> [AutoUpdate] Update dependency url-loader to version 2.1.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1073)
> [AutoUpdate] Update dependency karma-chrome-launcher to version 3.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1075)
> [AutoUpdate] Update dependency lodash to version 4.17.15.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1058)
> [AutoUpdate] Update dependency css-loader to version 3.1.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1067)
> [AutoUpdate] Update dependency file-loader to version 4.1.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1078)
> [AutoUpdate] Update dependency mocha-junit-reporter to version 1.23.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1082)
> [AutoUpdate] Update dependency raw-loader to version 3.1.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1085)
> [AutoUpdate] Update dependency react-redux to version 7.1.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1088)
> [AutoUpdate] Update dependency redux to version 4.0.4.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1092)
> [AutoUpdate] Update dependency webpack to version 4.37.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1086)
> [AutoUpdate] Update dependency react-swipeable to version 5.3.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1096)
> [Add Lib] Add types for react-facebook-login.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1094)
> [AutoUpdate] Update dependency webpack-dev-server to version 3.7.2.

- package.json
[AutoUpdate] Update dependency react-visibility-sensor to version 5.1.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1087)
> [AutoUpdate] Update dependency react-visibility-sensor to version 5.1.1.

- package.json
[AutoUpdate] Update dependency firebase to version 6.4.2.
[AutoUpdate] Update dependency firebase to version 6.3.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1115)
> [AutoUpdate] Update dependency firebase to version 6.5.0.

- package.json
[AutoUpdate] Update dependency firebase-tools to version 7.2.4.
[AutoUpdate] Update dependency firebase-tools to version 7.2.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1116)
> [AutoUpdate] Update dependency firebase-tools to version 7.3.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1111)
> [AutoUpdate] Update dependency eslint-loader to version 3.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1112)
> [AutoUpdate] Update dependency eslint-plugin-unicorn to version 10.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1098)
> [AutoUpdate] Update dependency @types/react-redux to version 7.1.2.

- package.json
[AutoUpdate] Update dependency @types/node to version 12.7.2.
[AutoUpdate] Update dependency @types/node to version 12.6.9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1100)
> [AutoUpdate] Update dependency @types/node to version 12.7.4.

- package.json
[AutoUpdate] Update dependency @types/lodash to version 4.14.137.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1099)
> [AutoUpdate] Update dependency @types/lodash to version 4.14.138.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1104)
> [AutoUpdate] Update dependency airtable to version 0.7.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1139)
> [AutoUpdate] Update dependency @babel/core to version 7.6.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1152)
> [AutoUpdate] Update dependency karma to version 4.3.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1146)
> [AutoUpdate] Update dependency detect-browser to version 4.7.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1165)
> [AutoUpdate] Update dependency webpack to version 4.39.3.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1164)
> [AutoUpdate] Update dependency typescript to version 3.6.3.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1151)
> [AutoUpdate] Update dependency js-cookie to version 2.2.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1161)
> [AutoUpdate] Update dependency react-test-renderer to version 16.9.0.

- doppins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1168)
> [Doppins] Use npm outdated to avoid too many calls to npm repo.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1155)
> [AutoUpdate] Update dependency radium to version 0.26.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1159)
> [AutoUpdate] Update dependency react-redux to version 7.1.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1174)
> [AutoUpdate] Update dependency firebase to version 6.6.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1144)
> [AutoUpdate] Update dependency @typescript-eslint/parser to version 2.2.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1150)
> [AutoUpdate] Update dependency imagemin to version 7.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1169)
> [AutoUpdate] Update dependency @mysticatea/eslint-plugin to version 12.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1172)
> [AutoUpdate] Update dependency eslint to version 6.4.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1162)
> [AutoUpdate] Update dependency style-loader to version 1.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1179)
> Add eslint plugin for react hooks.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1143)
> [AutoUpdate] Update dependency @hot-loader/react-dom to version 16.9.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1182)
> [AutoUpdate] Update dependency @types/lodash to version 4.14.141.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1145)
> [AutoUpdate] Update dependency css-loader to version 3.2.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1147)
> [AutoUpdate] Update dependency file-loader to version 4.2.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1175)
> [AutoUpdate] Update dependency puppeteer to version 1.20.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1183)
> [AutoUpdate] Update dependency @types/node to version 12.7.10.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1173)
> [AutoUpdate] Update dependency eslint-plugin-unicorn to version 11.0.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1156)
> [AutoUpdate] Update dependency react-google-login to version 5.0.5.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1157)
> [AutoUpdate] Update dependency react-hot-loader to version 4.12.13.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1158)
> [AutoUpdate] Update dependency react-lazyload to version 2.6.2.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1160)
> [AutoUpdate] Update dependency react-share to version 3.0.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1178)
> [AutoUpdate] Update dependency webpack-dev-server to version 3.8.1.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1184)
> [AutoUpdate] Update dependency @types/react-redux to version 7.1.4.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1198)
> [AutoUpdate] Update dependency eslint-plugin-react-hooks to version 2.1.2.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1200)
> [AutoUpdate] Update dependency firebase to version 7.1.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1201)
> [AutoUpdate] Update dependency firebase-tools to version 7.4.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1195)
> [AutoUpdate] Update dependency eslint to version 6.5.1.

- .circleci/config.yml
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1213)
> [CI] Add a simple CI and sort the package.json file.

- doppins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1211)
> [Doppins Tool] Make Bayes Impact Bot the author of the auto updates.

- .circleci/config.yml
- doppins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1238)
> [Doppins] Run doppins nightly on CircleCI, using a bot.

- doppins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1359)
> Fix Nightly runs.

- doppins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1409)
> [Doppins] Add changelog to message if present in repo.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1465)
> Add optional chaining to Babel

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1469)
> Drop react-loadable (use React.lazy instead).

- doppins.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1483)
> Clean up branches that are obsolete.

- cfg/base.js
- cfg/dev.js
- cfg/dist.js
- cfg/test.js
- server.js
- webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1550)
> [Webpack] Update webpack config to allow typescript files.

- cfg/base.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1551)
> [Webpack] Add whatwg-fetch to default entry.

- cfg/dist.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1562)
> [webpack] Fix dist config.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1579)
> Add concurrent lib for faster scripts.

- package.json
This reverts commit d5a4fbdfa0ef820b1593c60250c82710718b19e2.
This triggers errors for imports using a query string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1590)
> Revert "[AutoUpdate] Update dependency eslint-plugin-import to version 2.19.1. (#1584)"

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1655)
> Disable our Doppins to see if dependabot is enough.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1699)
> Adding react types to avoid depending on dependencies import.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1717)
> Adding new libs.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1723)
> Bump @sentry/browser.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1724)
> Delete duplicate version of @sentry/browser imported by @types/redux-sentry-middleware that is not always in sync with the main version.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1757)
> Bump @sentry/browser from 5.12.1 to 5.12.4

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1756)
> Add npm to the list of dependencies.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1760)
> Also clean up the yarn.lock when removing duplicate version of @sentry/browser

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/1818)
> Drop unused minimist.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2036)
> Push to Docker in CI, as Autobuild seems to have some trouble.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2042)
> Upgrade yarn-lazy-lock.

- .circleci/config.yml
- .circleci/test_other_repo.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2174)
> [CI] Run tests on projects depending on this one.

- .circleci/config.yml
Not sure what happened here. I believe the new review command doesn't work well when the base commit changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2182)
> [CI] Do the bob and cas-contact tests in parallel.

- .circleci/config.yml
- .circleci/tag.sh
- .circleci/test_other_repo.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2200)
> [BugFix] Drop the / in branches when tagging for docker.

- .circleci/tag.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2201)
> [CI] Drop all the slashes in branch name for tagging.

- CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2254)
> Add Emily as code owner, to get all the new reviews.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2352)
> [CI] Cache pupeteer install in docker.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2362)
> Use a low level npm install when preinstalling puppeteer.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2391)
> Add a dependent check on Ma Voie.

- .circleci/config.yml
- .circleci/test_other_repo.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2390)
> Allow custom job name for dependant repo.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2425)
> Add date-fns library.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2424)
> [CI] Drop dependent checks for BLC.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2426)
> Drop moment since we use date-fns.

- .babelrc
- cfg/dev.js
- cfg/dist.js
- cfg/test.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2460)
> Fix options of @babel/env to properly use polyfill of core-js v3.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2194)
> [Doc] Update README to talk about the CI process.

- .circleci/config.yml
- .circleci/test_other_repo.sh
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2415)
> [CI] Only run dependant tests asynchronously and on master.

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2585)
> Add Chrome libs for headless testing.

- package.json
This reverts commit 2a47d0df312ca1ea5ec82b19bda99e5426fb508d.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2698)
> Revert "Bump react-i18next from 11.7.4 to 11.8.2 (#2697)"

- package.json
- webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/2788)
> Drop the use of es6-promise as it's covered by babelrc and corejs

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3194)
> Fix the double dep on webpack again.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3196)
> Build Docker container with buildkit.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3216)
> Keep the resolution of @sentry/browser up to date with the installed version.

- .circleci/config.yml
- .circleci/test_resolutions.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3217)
> Test that resolutions are in sync with dependencies.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3239)
> [Master Main] Migrate repo to use ‘main‘ as default branch.

- .circleci/config.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3297)
> [Master Main] Clean last master references.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3412)
> Bump @sentry/browser from 6.9.0 to 6.10.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3449)
> Bump webpack from 5.46.0 to 5.49.0.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3579)
> [Small Fix] Align sentry resolution with its actual version.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3639)
> Publish tag latest when main branch is updated.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3776)
> Upgrade to React v17.0.2

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3896)
> Add saas libraries used in Bob.

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/docker-react/3964)
> Add @types/react-dom (previously imported by @types/react-select).
